services:
  - type: web
    name: bidhub-backend
    env: node
    plan: free
    buildCommand: cd bidhub-backend && npm install
    startCommand: cd bidhub-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: "*"
      - key: DB_HOST
        value: bidhub-bidhub.b.aivencloud.com
      - key: DB_PORT
        value: 27575
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: NO_PROXY
        value: bidhub-bidhub.b.aivencloud.com
      - key: no_proxy
        value: bidhub-bidhub.b.aivencloud.com
    healthCheckPath: /api/health
    autoDeploy: true
    branch: listmng
